baseurl = "/"
relativeurls = true
languageCode = "en-gb"
title = "ContinuousPipe Docs"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyURLs = false
googleAnalytics = ""
PygmentsCodeFences = true

[params]
	# General information
	author = "Samuel Rozé"
	description = "Documentation for ContinuousPipe"
	copyright = "Released under the MIT license"

	#version = "1.0.0"
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = [ "https://cdn.jsdelivr.net/docsearch.js/2/docsearch.min.css","stylesheets/custom.css" ]
	custom_js  = [ "https://cdn.jsdelivr.net/docsearch.js/2/docsearch.min.js", "javascripts/jquery-3.1.1.min.js" , "javascripts/menu.js" ]

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "blue"
    	accent  = "teal"

    [params.font]
    	text = "Open Sans"
    	code = "Ubuntu Mono"

[social]
	twitter = "continuouspipe"
	github  = "continuouspipe"
	email   = "support@continuouspipe.io"

[[menu.main]]
	name   = "Basics"
	url    = "/basics/"
	identifier = "basics"
	weight = "5"

[[menu.main]]
	name   = "Quick Start"
	url    = "/quick-start/"
	identifier = "quick-start"
	weight = "10"

[[menu.main]]
	name   = "Configuration"
	url    = "/configuration/"
	identifier = "configuration"
	weight = "15"

[[menu.main]]
	name   = "FAQ"
	url    = "/faq/"
	identifier = "faq"
	weight = "20"
